services:
  app:
    build: .
    ports:
      - "5000:5000"
    networks:
      - monitor

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitor

  grafana:
    image: grafana/grafana
    environment:
      - GF_LOG_LEVEL=warn
    ports:
      - "3000:3000"
    networks:
      - monitor

  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
    networks:
      - monitor

networks:
  monitor:
