{
 "title": "Age-Checker application",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "illegal age requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "illegal_age_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "legal app request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "legal_age_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "total request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "total_requests_total", "legendFormat": "__auto" }
   ]
  }
 ]
}