name: CI Pipeline

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Unit Tests
        run: |
          python -m unittest discover -s app

      - name: Run Lint
        run: |
          pip install flake8
          flake8 app

      - name: Build Docker Image
        run: docker build -t starter-app .